apiVersion: v2
name: sow-rest-api
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
maintainers:
  - email: hrsi88@gmail.com
    name: Yarden Shoham
sources:
  - https://github.com/k8-proxy/sow-rest-api
