apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icap-adaptation
  name: rebuild-rest-api
spec:
  selector:
    matchLabels:
      app: rebuild-rest-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rebuild-rest-api
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"  
      containers:
      - name: rebuild-rest-api
        image: ggrig/sow-rest-api:0.01
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: ProcessingTimeoutDuration
          value: "00:01:00"
        - name: OriginalStorePath
          value: "/var/source"
        - name: RebuiltStorePath
          value: "/var/target"
        - name: ExchangeName
          value: "adaptation-exchange"
        - name: RequestQueueName
          value: "adaptation-request-queue"
        - name: OutcomeQueueName
          value: "amq.rabbitmq.reply-to"
        - name: RequestMessageName
          value: "adaptation-request"
        - name: MBHostName
          value: "rabbitmq-service"
        - name: MBPort
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  namespace: icap-adaptation
  name: rebuild-rest-api
  labels:
    service: rebuild-rest-api
spec:
  selector:
    app: rebuild-rest-api
  ports:
    - name: http
      port:  80
  type: ClusterIP      
